-- AlterTable
ALTER TABLE "server" ADD COLUMN     "m_cpu" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "m_disk" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "m_gpu" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "m_ram" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "m_temp" BOOLEAN NOT NULL DEFAULT true;
